### PR TITLE
fix(tsconfig): add  exactOptionalPropertyTypes

### PR DESCRIPTION
**Pull request by douglasduteil**
### Additional context

---

### What is the purpose of this pull request?

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/jrgarciadev/tailwind-variants/blob/main/CONTRIBUTING.md).
- [x] Follow the [Style Guide](https://github.com/jrgarciadev/tailwind-variants/blob/main/CONTRIBUTING.md#style-guide).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

### CODE REVIEW

**Comment by mskelton** [comment]
Why?

**Comment by douglasduteil** [comment]
I experimented some issues with `tailwind-variants` and this compiler options. 
I'm wandering if the same errors hit the `tailwind-variants` tests.

Some like : 
```tsx

import { tv, type VariantProps } from "tailwind-variants";

const button = tv({
  variants: {
    intent: {
      primary: "bg-primary"
    }
  }
})

function DatButton({ intent }:  VariantProps<typeof button>) {
  return <button className={button({ intent })} />
}
```

Result with : 
```txt
Type error: Argument of type '{ intent: "primary" | undefined;  }' is not assignable to parameter of type '({ intent?: "primary" } & ClassProp<...>) | undefined'.
  Type '{ intent: "primary" | undefined;  }' is not assignable to type '{ intent?: "primary" } & { ...; }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
    Type '{ intent: "primary" | undefined;  }' is not assignable to type '{ intent?: "primary" }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
      Types of property 'intent' are incompatible.
        Type '"primary" | undefined' is not assignable to type '"primary"'.
          Type 'undefined' is not assignable to type '"primary"'.
```

**Comment by mskelton** [comment]
@douglasduteil Thanks for the example. I updated the type decls to support `exactOptionalPropertyTypes`

**Review by douglasduteil — COMMENTED** [review]
Looks perfect @mskelton  :)

**Review by mskelton — APPROVED** [review]

**Comment by douglasduteil** [comment]
🎉  Thanks @mskelton

**Pull request merged**
